### ISSUE TITLE
Bug: Fave count not showing on project pages

### ISSUE THREAD

**Issue by return-misaPuding** [CluckCluckChicken/spyglass-2#5]
Description:
On project pages, you can see the number of favs and loves the project has, but the fave count is always 0, even tho the project has like 4000+ favs
Screenshots:
![magnifier-project-faves-bug-1-2-projectID_531663489](https://user-images.githubusercontent.com/70533713/140174818-690e626e-113d-4390-a00c-71afe3f1689e.png)
![magnifier-project-faves-bug-1-1-projectID_531663489](https://user-images.githubusercontent.com/70533713/140174834-007fc35d-5157-4261-913e-cf45feb2635e.png)
Expected behaviour: The real fave count should be visible next to the star icon
Actual behaviour: A zero is displayed next to the star icon instead

**Comment by CluckCluckChicken** [comment]
i was accidentally using the proper spelling for "favourites" instead of fake version ("favorites"). this is fixed.
